"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = [
    ('static/permanent/', ['static/permanent/fulldir.csv']),
    ('templates', ['templates/index.html']),
    ('static/csv/csvs', ['static/csv/csvs/newfile.csv'])
]
OPTIONS = {
    'packages': ['pandas', 'jinja2', 'flask', 'flask_uploads', 'plotly']
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
